# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto
xrandr --output eDP-1 --brightness 0.5
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom &
greenclip daemon &
xss-lock -- i3lock-fancy -n &
dunst &
flameshot &
emacs --daemon &
exec qtile start
