[mgr]
prepend_keymap = [
  { on = ["\\", "t", "p"], run = "plugin toggle-pane min-preview", desc = "Toggle Preview" },
  { on = ["\\", "t","m"], run = "plugin toggle-pane max-preview", desc = "Max Toggle Preview" },

  { on = ["\\", "d"], run = '''shell --orphan -- dragon-drop -x -T "$@"''', desc = "Drag&Drop" },
  # { on = ["\\", "l"], run = '''linemode size''', desc = "No Linemode" },

  { on = ["M","m"], run = "plugin sshfs -- mount --jump",    desc = "Mount & jump" },
  { on = ["M","u"], run = "plugin sshfs -- unmount",         desc = "Unmount SSHFS" },
  { on = ["M","a"], run = "plugin sshfs -- add",             desc = "Add SSH host" },
  { on = ["M","r"], run = "plugin sshfs -- remove",          desc = "Remove SSH host" },
  { on = ["M","h"], run = "plugin sshfs -- home",            desc = "Go to mount home" },
  { on = ["M","c"], run = "cd ~/.ssh/",                      desc = "Go to ssh config" },
  { on = ["g","m"], run = "plugin sshfs -- jump",            desc = "Jump to mount" },
]
