#!/bin/sh

OUTPUT="${2:-eDP-1}"

brightness=$(
    xrandr --verbose |
    awk -v out="$OUTPUT" '
        $1 == out { found=1 }
        found && /Brightness:/ {
            print $2
            exit
        }
    '
)

case "$1" in
    up)
        step=$(awk -v b="$brightness" 'BEGIN {
            if (b >= 1) print 0.1;
            else print 0.05;
        }')

        brightness=$(awk -v b="$brightness" -v s="$step" 'BEGIN {
            b += s;

            if (b > 2)
                b = 2;

            printf "%.2f", b;
        }')
        ;;

    down)
        step=$(awk -v b="$brightness" 'BEGIN {
            if (b > 1) print 0.1;
            else print 0.05;
        }')

        brightness=$(awk -v b="$brightness" -v s="$step" 'BEGIN {
            b -= s;

            if (b < 0)
                b = 0;

            printf "%.2f", b;
        }')
        ;;
esac

xrandr --output "$OUTPUT" --brightness "$brightness"

echo "$brightness"

send_notification() {
    percentage=$(awk -v b="$brightness" 'BEGIN {
        printf "%.0f", b * 100
    }')

    HLCOLOR="#cccccc"
    ICON="brightness-display-symbolic"

    notify-send \
        -a "Brightness" \
        -r 10002 \
        -h int:value:"$percentage" \
        -h string:hlcolor:"$HLCOLOR" \
        -i "$ICON" \
        "Brightness" \
        "${percentage}%" \
        -t 2000
}

send_notification
