#!/bin/bash

check_italics () {
    echo -e "\e[3mThis is italic text\e[0m"
    echo -e "\e[3;34mThis is blue italic text\e[0m"
    echo -e "\e[1;3;31mThis is red bold italic text\e[0m"
}

check_undercurl () {
    echo -e "\e[4:3mThis text has an undercurl\e[0m"
    echo -e "\e[4:3;38;5;196mRed text with Red Undercurl\e[0m"
    echo -e "\e[38;5;82m\e[4:3m\e[58;5;196mGreen Text with Red Undercurl\e[0m"
}

check_strikethrough () {
    echo -e "\e[9mThis text has a strikethrough\e[0m"
    echo -e "\e[9;38;5;196mRed text with Red strikethrough\e[0m"
}

check_special_escapes () {
    check_italics
    check_undercurl
    check_strikethrough
}

check_special_escapes
