#!/bin/sh

chosen=$(printf "  \n  \n  \n  鈴" | rofi -dmenu -i -theme-str '@import "powermenu.rasi"')

case "$chosen" in
  "  ") systemctl poweroff ;;
    "  ") systemctl reboot ;;
    "  ") i3lock-fancy;;
    "  鈴") systemctl suspend ;;
    *) exit 1 ;;
esac
