local ok, wk = pcall(require, "which-key")
if not ok then
    return
end
wk.register({
    ["1"] = { "Buffer 1" },
    ["2"] = { "Buffer 2" },
    ["3"] = { "Buffer 3" },
    ["4"] = { "Buffer 4" },
    ["5"] = { "Buffer 5" },
    ["6"] = { "Buffer 6" },
    ["7"] = { "Buffer 7" },
    ["8"] = { "Buffer 8" },
    ["9"] = { "Buffer 9" },
    ["/"] = { "Comment" },
    g = {
        name = "Git",
        h = { ":SignifyToggleHighlight<cr>", "Highlight" },
        t = { ":SignifyToggle<cr>", "Toggle" },
        s = { ":G<cr>", "Status" },
        d = { ":Gvdiffsplit<cr>", "DiffSplit" },
        D = { ":G diff<cr>", "Diff" },
        a = { ":Gw<cr>", "Add" },
        A = { ":G add .<cr>", "AddCDir" },
        r = { ":GDelete<cr>", "Remove" },
        R = { ":GRename<cr>", "Rename" },
        c = { ":G commit<cr>", "Commit" },
        p = { ":G push<cr>", "Push" },
        P = { ":G pull<cr>", "Pull" },
        f = { ":G fetch<cr>", "Fetch" },
        l = { ":Gclog<cr>", "Log" },
        C = { ":GBranches<cr>", "Checkout" },
        bb = { ":G blame<cr>", "Blame" },
        B = { ":GBrowse<cr>", "Browse" },
        cc = { ":GV!<cr>", "Commits" },
        CC = { ":GV<cr>", "AllCommits" },
        F = { ":G add<Space>", "CustAdd" },
        m = { ":GMove<Space>", "Move" },
        b = { ":G branch ", "Branch" },
    },
    e = { ":NvimTreeFindFileToggle<cr>", "Explorer" },
    f = {
        name = "Telescope",
        f = { "<cmd>Telescope find_files<cr>", "Files" },
        r = { "<cmd>Telescope oldfiles<cr>", "Recent" },
        g = { "<cmd>Telescope live_grep<cr>", "Grep" },
        h = { "<cmd>Telescope help_tags<cr>", "Help" },
        C = { "<cmd>Telescope git_commits<cr>", "Commits" },
        G = { "<cmd>Telescope git_files<cr>", "Git Files" },
        B = { "<cmd>Telescope git_branches<cr>", "Branches" },
        s = { "<cmd>Telescope git_status<cr>", "Status" },
        c = { "<cmd>Telescope commands<cr>", "Commands" },
        b = { "<cmd>Telescope buffers<cr>", "Buffers" },
        d = { "<cmd>Telescope diagnostics<cr>", "Diagnostics" },
        m = { "<cmd>Telescope marks<cr>", "Marks" },
        M = { "<cmd>Telescope man_pages<cr>", "Man" },
    },
    h = {
        name = "Hunk",
        s = "Stage Hunk",
        S = "Stage Buffer",
        r = "Reset Hunk",
        R = "Reset Buffer",
        u = "Undo Stage Hunk",
        p = "Preview Hunk",
        t = "Toggle Hunk",
        b = "Blame Line",
        B = "Blame Line full",
        T = "Blame Line Toggle",
        d = "DiffSplit",
        D = "DiffSplit ~",

    },
}, { prefix = "<leader>" })
wk.setup()
