[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7f8c8d"
blue = "#3daee9"
cyan = "#16a085"
green = "#1cdc9a"
magenta = "#8e44ad"
red = "#c0392b"
white = "#ffffff"
yellow = "#fdbc4b"

[colors.dim]
black = "#31363b"
blue = "#1b668f"
cyan = "#186c60"
green = "#17a262"
magenta = "#614a73"
red = "#783228"
white = "#63686d"
yellow = "#b65619"

[colors.normal]
black = "#232627"
blue = "#1d99f3"
cyan = "#1abc9c"
green = "#11d116"
magenta = "#9b59b6"
red = "#ed1515"
white = "#fcfcfc"
yellow = "#f67400"

[colors.primary]
background = "#232627"
bright_foreground = "#ffffff"
dim_foreground = "#eff0f1"
foreground = "#fcfcfc"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[font]
size = 8.5

[font.bold]
family = "Mononoki Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[window]
opacity = 0.84

[window.dimensions]
columns = 140
lines = 30

[window.padding]
x = 1
y = 1
